- name: Phil's append to cmdline.txt 
  gather_facts: false
  hosts: raspi-cluster
  tasks: 
    - ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt  
        regex: '‘^ [\t ]cgroup_enable=.*’'
        line: 'cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
        insertafter: EOF
        backrefs: yes
